### ISSUE TITLE
How to connect to bucketFS?

### ISSUE THREAD

**Issue by tjlee** [EXASOL/docker-db#11]
Is there any way to connect to bucketFS if Exasol in docker container? What's default write password?
Thank you.

**Comment by ooke** [comment]
You have the EXAConf file, in it you have the `BucketFS` category and in it there are `ReadPassword` and `WritePassword` configurations with passwords in Base64, you can decode it with something like:
```
$> echo "Skx6UUg4UjQyOWIxUGw5ek9GdUFqWQ==" | base64 -d; echo
```
