### ISSUE TITLE
Failed to create volume: insufficient space

### ISSUE THREAD

**Issue by sztanko** [EXASOL/docker-db#14]
Hello,

I am hitting a strange problem when configuring the cluster without --auto-storage option.

If using --auto-storage, the cluster will start up, but at around size of /exa volume hits  35GiB, it crashes with "device full" error.

All this happens on Google Cloud instance with 200GiB disk and 25GiB RAM running Debian.

Here are the results of running [exasol_info.tar.gz](https://github.com/EXASOL/docker-db/files/1898528/exasol_info.tar.gz)

Thank you very much!

## What were you doing before the error occurred?
> SIZE="50GiB"
> DOCKER_DB_PATH=/home/demetersztanko
> 
> $DOCKER_DB_PATH/docker-db/exadt stop-cluster MyCluster
> echo y | $DOCKER_DB_PATH/docker-db/exadt delete-cluster MyCluster
> 
> 
> $DOCKER_DB_PATH/docker-db/exadt create-cluster --root ~/MyCluster/ --create-root MyCluster
> $DOCKER_DB_PATH/docker-db/exadt init-cluster --image exasol/docker-db:latest --license $DOCKER_DB_PATH/docker-db/license/license.xml MyCluster
> $DOCKER_DB_PATH/docker-db/exadt create-file-devices --size $SIZE MyCluster
> 
> # here you configure disks
> sed -e "s/\[SIZE\]/$SIZE/g" EXAConf.template > MyCluster/EXAConf
> $DOCKER_DB_PATH/docker-db/exadt start-cluster MyCluster
> docker logs -f MyCluster_11

## What did you expect to happen?
A running cluster with 50GB disk space.

The machine I was running docker on had 193GiB free space available:

> demetersztanko@exasol-docker:~$ df -h
> Filesystem      Size  Used Avail Use% Mounted on
> udev             64M     0   64M   0% /dev
> tmpfs           2.6G   12M  2.6G   1% /run
> /dev/sda1       197G  6.3G  183G   4% /
> tmpfs            13G     0   13G   0% /dev/shm
> tmpfs           5.0M     0  5.0M   0% /run/lock
> tmpfs            13G     0   13G   0% /sys/fs/cgroup

## What actually happened?
The database doesn't start, 
docker logs -f MyCluster_11 show this:

> [2018-04-11 11:02:16] stage3: Run service storage_volumes
> Traceback (most recent call last):
>   File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.8/libexec/exainit.py", line 79, in <module>
>     main(sys.argv)
>   File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.8/libexec/exainit.py", line 71, in main
>     run(args[1])
>   File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.8/libexec/exainit.py", line 45, in run
>     serv.run_result = serv.run()
>   File "/usr/opt/EXASuite-6/EXAClusterOS-6.0.8/exainit/tasks/storage.py", line 162, in run
>     'hdd_type': volinfo.disk})
>   File "services/storage/interface/libCS_interface_py.pxi", line 646, in libCS_py.storage.create_volume (.build/services/storage/interface/libCS_py.cc:9522)
> Exception: Failed to create volume: insufficient space
> [2018-04-11 11:02:17] root child 39 returned with state 1.

**Comment by sztanko** [comment]
Apologies for premature submission, I have resolved the issue.
I was assigning the same size for device and for disks, and of course it was running out of space, since there are two disks on the device.

Setting the device size two double has resolved the issue.

Apologies again and thank you for creating such an amazing product!

**Comment by exajuk** [comment]
No problem :wink: 

Let me add a note that may help you in the future: not 100% of an EXAStorage device is actually usable, because some sectors are reserved for checksums! With a 50 GiB device, about 49,95 GiB are actually available for volumes. That's why choosing volume-size == device-size will usually fail. 

According to the logs, that's exactly what happened in your case, i. e. the creation of the first volume failed because only 49,95 GiB was free on the device...
