### ISSUE TITLE
Unable to restart exasol container in kubernetes

### ISSUE THREAD

**Issue by nepux** [exasol/docker-db#17]
We have problems to get a unmodifed version of the docker image running in Kubernetes after a pod restart. (pods in kubernetes getting a new ip adresse on every restart)

The problem is related to the interface lookup and the private network setting.

If we setup a proper network with a valid prefix, it fails with 

```
                log_err("exadt::ERROR: the private interface with address '%s' either does not exist or is down." 
% (priv_net))
```
due to a faulty comparison.  network prefix vs. network address

https://github.com/EXASOL/docker-db/blob/cf96009c66e0be046605e2e4dbf8e3213b806dbd/exadt#L410

**Comment by nepux** [comment]
Good Morning,

the code compares strings instead of networks.

10.10.10.**11**/24  and 10.10.10.**123**/24 are the same networks.
255.255.255.0 == 255.255.255.0

If iI set a private Network like 10.1.1.0/24, the code fails for all addresses in the network 10.1.1.0/24 (10.1.1.1 - 10.1.1.254) except  10.1.1.0/24

The point is, i can ensure that the docker container is part of a network but i cant ensure a specific ip.

**Comment by exajuk** [comment]
Hi!

 The mechanism currently requires that the **IP address** of each node is specified in EXAConf (not just the network). This is necessary for multi-node / multi-container communication and thus can't be changed. 

However, it would be possible to skip the check (and update the IP instead) in case of a single container (i e. only one node entry in EXAConf). Would that solve your problem? I. e. does the container start if you enter the correct IP in EXAConf?

If you'd describe your kubernetes setup / usage scenario in more detail, we could improve support for it in the future...

**Comment by exajuk** [comment]
Closed due to inactivity.
