### ISSUE TITLE
BucketFS: File '/buckets/bfsdefault/default/EXASolution-6.0.0/exaudfclient' does not exist

### ISSUE THREAD

**Issue by nightscape** [EXASOL/docker-db#2]
Hi again!

For our development process, we'd like to create a pre-migrated and ready-to-use Exasol image.
We are using MyBatis to run some DDL statements against the DB, but unfortunately on some machines this fails with the following error:
```
ERROR: Error executing command.  Cause: org.apache.ibatis.jdbc.RuntimeSqlException: Error executing: CREATE OR REPLACE PYTHON SCALAR SCRIPT dwh_partitions.py_generate_uuid_char_base64()
RETURNS CHAR(22) CHARACTER SET ASCII AS
import uuid
import base64
def run(ctx):
  return base64.b64encode(uuid.uuid4().bytes)[:-2]
/

.  Cause: java.sql.SQLException: BucketFS: File '/buckets/bfsdefault/default/EXASolution-6.0.0/exaudfclient' does not exist. (Session: 1565754778663861959)
```
The `exaudfclient` file seems to exist although separated by a `:` in the path instead of a `/`:
```
# find /exa/data/bucketfs/ | grep exaudf
/exa/data/bucketfs/bfsdefault/default/EXASolution-6.0.0:exaudf.jar
/exa/data/bucketfs/bfsdefault/default/EXASolution-6.0.0:exaudfclient
```

One machine where this is failing is running `Docker version 17.04.0-ce, build 4845c567eb`, one machine where it is working runs `Docker version 1.12.3, build 6b644ec`.
Could this be Docker version related? Or might something else be going on?

Thanks!

**Comment by ooke** [comment]
Hi!

The path `/exa/data/bucketfs/bsfdefault/default` is used as source, but real data are in the `.dest` directory. On my system your find gives following:
```
$ docker exec -it dreamy_visvesvaraya /bin/bash
[root@n11 /]# find /exa | grep exaudfclient                                                                                                                                                                                                                                                                                   
/exa/data/bucketfs/bfsdefault/default/EXASolution-6.0.0:exaudfclient
/exa/data/bucketfs/bfsdefault/.dest/default/EXASolution-6.0.0/exaudfclient
[root@n11 /]# 
```

Your problem seems to be, that you have waited not long enough. On each start, this package need to be extracted:
```
# ls -lh /exa/data/bucketfs/bfsdefault/default/EXAClusterOS\:ScriptLanguages-2017-01-30.tar.gz 
-rwxr-xr-x 1 u00500 g00500 494M Apr 27 08:40 /exa/data/bucketfs/bfsdefault/default/EXAClusterOS:ScriptLanguages-2017-01-30.tar.gz
```

It contains the environment for UDFs and it can take some time, especially on somewhat slower machines. This is a point to be optimized in future versions.

Best regards
Oleksandr

**Comment by nightscape** [comment]
Hi Oleksandr,

correct again! If I start the container manually and wait for a while, the file in `.dest` appears.
Is there a way (e.g. an SQL statement) to ask Exasol if it has already finished unpacking the required stuff?

**Comment by ooke** [comment]
Unfortunately it is no API there to check it.

But you can define and run an dummy UDF, if it worked without errors, than everything work, if not, you need to wait a bit.

**Comment by nightscape** [comment]
Fair enough. We adapted the script that waits until it can connect to EXASOL to check if it can create a script now.
Thanks for your help!
