### ISSUE TITLE
start and connect instructions are not clear

### ISSUE THREAD

**Issue by Volodymyrk** [EXASOL/docker-db#23]
After running `docker run --name exasoldb -p 127.0.0.1:8899:8888 --detach --privileged --stop-timeout 120  exasol/docker-db:latest` it is not clear how to connect to a DB.
Can you please provide an example of the connection string with URL, default login and password please?

**Comment by exajuk** [comment]
Connecting to the database in an Exasol Docker container is not different from the "normal" version. The default username is `sys`, the default password is `exasol`. Please refer to the official manual for further information: https://www.exasol.com/portal/display/DOC/Database+User+Manual
