### ISSUE TITLE
Oracle Driver installation not working

### ISSUE THREAD

**Issue by thinking-aloud** [EXASOL/docker-db#24]
I failed to install the Oracle instant client inside the exasol Docker container.

`curl -v -X PUT -T instantclient-basic-linux.x64-12.1.0.2.0.zip http://w:PASSWORD@10.10.10.11:6583/default/drivers/oracle/instantclient-basic-linux.x64-12.2.0.1.0.zip`

Since the mentioned curl command did not work, I pasted the zip in the appropriate directory:
`/exa/data/bucketfs/bfsdefault/default/drivers/oracle/`
Reading from the documentation, that should be enough. However, since it did not work, I also tried to unzip the file.

My version is: exasol/docker-db:6.0.12-d1
I tried both version 12.2.0.1.0 and version 12.1.0.2.0 since the version is being used inconsistently in the documentation.

I am also not sure, if I need a settings file like mentioned for jdbc. If yes, where do I have to put it and what is the content of the file.

Ps. Some clarification wold be great.

**Comment by exajuk** [comment]
Hi!

There are indeed some typos in our README regarding the version number (they will be fixed). The correct version is `12.1.0.2.0`. However, you have to upload the driver package via BucketFS. A manual upload will not work.

Please provide the output of the `curl` command (including the command itself), so we can see the actual error message.

**Comment by thinking-aloud** [comment]
@exajuk I tried the curl from the machine the docker container is running on and now it worked. Thank you.
