### ISSUE TITLE
Wrong search path for database drivers

### ISSUE THREAD

**Issue by HEP85** [exasol/docker-db#26]
Using the image version 6.0.12-d1, I left all settings in EXAConf for the buckets at their defaults:

- BucketFS = bfsdefault
- Bucket = default
- JDBC: Dir = drivers/jdbc
- Oracle: Dir = drivers/oracle

I uploaded the drivers with curl into the BucketFS into the folder given in the README, but the drivers are not found. SQL Session log shows, that there are searched for in the wrong path.

JDBC was looked for here: **/exa/data/bucketfs/default/drivers/jdbc**
JDBC actual location: **/exa/data/bucketfs/bfsdefault/.dest/default/drivers/jdbc**

Oracle was looked for here: **/usr/opt/EXASuite-6/3rd-party/Oracle/instantclient_12_1**
Oracle actual location: **/exa/data/bucketfs/bfsdefault/.dest/default/drivers/oracle/instantclient-basic-linux.x64-12.1.0.2.0**

Symlinking the wrong path to the correct one works around the problem, but since the Oracle location is on the non-persistent folder, the workaround for the Oracle driver is lost when restarting the cluster.

**Comment by exajuk** [comment]
Fixed in https://github.com/exasol/docker-db/releases/tag/6.1.2-d1.
