### ISSUE TITLE
Basic issue: cannot access standalone EXASOL in docker

### ISSUE THREAD

**Issue by roedelk** [exasol/docker-db#27]
Hi there,

for test purposes I have downloaded the latest EXASOL docker image and tried to get it running in a standalone mode:
`docker run --name exasoldb  -p 127.0.0.1:8899:8888 --detach --privileged --stop-timeout 120 -v %DOCKER_HOME%/exa_vol:/exa exasol/docker-db:latest`

However, I was not able to login via the Exaplus GUI on Windows 10 (Connection refused).
So I tried the commandline access as described 
`docker exec -it 8e8367d5c253 exaplus -c localhost:8888 -u sys -P exasol`
> OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"exaplus\": executable file not found in $PATH": unknown

Assuming this must be an issue in the image configuration, I logged into the container and searched for the complete path. But got the same error:
>[root@n11 Console]# cd /usr/opt/EXASuite-6/EXASolution-6.0.11/bin/Console/
>[root@n11 Console]# ./exaplus -c localhost:8888 -u sys -P exasol
>EXAplus 6.0.10 (c) EXASOL AG
>Error: [08001] Connection refused (Connection refused)

Looking into the configuration area, no success either: 
>[root@n11 /]# dwad_client list
>DWAd channel did not get available within 10 seconds.

Any suggestions? Did I got the wrong image? Or am I missing something essential here?

Cheers Kolja

**Comment by wildraid** [comment]
Please try to connect to port 8899 instead.

```
./exaplus -c localhost:8899 -u sys -P exasol
```

You may use local ExaPlus client. No need to run it from container.

**Comment by roedelk** [comment]
> 
> Please try to connect to port 8899 instead.
> 
> ```
> ./exaplus -c localhost:8899 -u sys -P exasol
> ```
> 
> You may use local ExaPlus client. No need to run it from container.

Thanks for support, but unfortunately it did not work:
`C:\Program Files (x86)\Exasol\EXASolution-6.0\EXAplus>exaplus -c localhost:8899 -u sys -P exasol`
`Can not find the Java Runtime Environment needed by EXAplus.`
`Trying to use system wide virtual machine (from registry) instead.`
`No 32 bit java virtual machine found in registry.`

`C:\Program Files (x86)\Exasol\EXASolution-6.0\EXAplus>exaplusx64 -c localhost:8899 -u sys -P exasol`
`EXAplus 6.0.10 (c) EXASOL AG`
`Error:  [08001] Connection refused.`

Further ideas?

**Comment by wildraid** [comment]
@roedelk , I've just noticed this paragraph in documentation:

```
exadt currently only supports Docker on Linux. If you are using a Windows host you'd have to create a Linux VM.

The host OS must support O_DIRECT access for the EXASOL containers, which may not be the case for Docker on Mac (see Troubleshooting).
```

Maybe Exasol is not actually starting in docker on Windows and does not accept connections in the first place.

**Comment by wildraid** [comment]
@roedelk , if it's purely for testing purposes and Windows is the only (sad) option, you may use this guide for Community Edition: https://www.exasol.com/portal/display/DOC/EXASOL+Community+Edition+Quick+Start+Guide

**Comment by exajuk** [comment]
@wildraid is right: Windows is not supported (or tested) at all. It's best to use a Linux VM if you're limited to a Windows host. Also, one of the first things to check (if there's a problem) is the output of `docker logs`...
