### ISSUE TITLE
Storing IP?

### ISSUE THREAD

**Issue by pbel78** [exasol/docker-db#29]
Picking up the problem from issue #17: we use single node docker instances for development and testing of the Datavault Builder software. But as you wrote it seams the container checks for the ip . With docker-compose down and up it happens on our servers that the container gets reassigne a new ip address and the db is not reachable anymore. You wrote that this can be disabled? How would we do that? Is there an env setting?

Thanks
Petr

**Comment by HEP85** [comment]
This is perfectly avoidable using Just Docker configuration settings. Go to https://docs.docker.com/compose/compose-file/ and look at zur section IPV4_ADDRESS, IPV6_ADDRESS. You will find an example on how to set a static IP dir the container.

**Comment by pbel78** [comment]
Thank you.
