### ISSUE TITLE
Missing documentation on adding reserve node

### ISSUE THREAD

**Issue by HEP85** [exasol/docker-db#31]
It ist unclear how to edit EXAConf to add a reserve node. Could you please add an example to the README?

**Comment by exajuk** [comment]
Hi! 

 In the `[DB : ]` section you can configure a list of nodes and a number of master nodes. If there are more nodes in the list than the nr. of master nodes, the remaining nodes are used as reserve nodes. 

Example:
```
Nodes = n11, n12, n13
NumMasterNodes = 2
```
The DB will be started on nodes n11 and n12, while n13 will be added as a reserve node. 

Note that you currently need to restart the container / cluster for this to take effect!

**Comment by exajuk** [comment]
The next version will contain (hopefully) helpful comments regarding DB reserve node configuration in the DB section of EXAConf.
