### ISSUE TITLE
Separate "latest" tags for major Exasol versions

### ISSUE THREAD

**Issue by wildraid** [exasol/docker-db#32]
Hello.

Could you please create and maintain separate tags on Docker Hub for each Exasol major version (6.0 and 6.1 at this moment)? It is important for automated testing. We'll be able to run tests against latest versions of each major branch.

Thank you.

**Comment by exajuk** [comment]
The `latest` tag is only added to the latest Docker image of the latest major version, currently `6.1.3`. I. e. `6.0.x` versions never get the `latest` tag. Are you suggesting to introduce `latest-6.0`?

**Comment by wildraid** [comment]
Ideally, I would love to have "latest-6.0" and "latest-6.1". And "latest-6.2" to be added after release of next major branch this year. It would be very clear and easy to maintain.

Thank you.

**Comment by exajuk** [comment]
OK, got it ;-) But note that the `6.0.x` branch didn't get any Docker related updates for quite some time (and it won't get any in the future). We strongly recommend to switch to `6.1.x`.

**Comment by ooke** [comment]
It will be the case in future.
