### ISSUE TITLE
Exasol 6.2 Beta

### ISSUE THREAD

**Issue by pbel78** [exasol/docker-db#34]
Hi

Do you have already plans for releasing a Exasol 6.2 Beta release. Background are the lockfree metadata queries which we like to try as we assume this will fix some of our failing regression tests.

Thanks
Regards
Petr

**Comment by wildraid** [comment]
"Lock-free" snapshot transactions are available in earlier Exasol versions.

It's not officially documented, but uou may try to use it and see how it goes: https://github.com/badoo/pyexasol/blob/master/docs/SNAPSHOT_TRANSACTIONS.md

**Comment by pbel78** [comment]
Thank you for the advise. I assume so it will be available in the 6.1.3 container? 

But as we currently mix read and write operations. Is there an option also to change the isolation level within a active connection?  (I think something like in other databases: SET TRANSACTION ISOLATION LEVEL xyz?

**Comment by wildraid** [comment]
In theory, you may switch `snapshot_transaction` ON and OFF using direct `.set_attr()` calls. But I strongly advise against doing so, since potential side-effects are unknown.

It's a good idea to open separate connection and use it for meta-requests only.

**Comment by exajuk** [comment]
https://github.com/exasol/docker-db/releases/tag/6.2.0-d1
