### ISSUE TITLE
Internal Server Error in Docker 6.1.3.d not happening in VM Version

### ISSUE THREAD

**Issue by pbel78** [exasol/docker-db#35]
We're looking for the reason (and how to prevent it) of the 'internal server error' shown in the following log entry (exasol docker container with tag 6.1.3-d1):
in logs/db/DB1/.logbackup/log_server190612103706.tgz/20190612_095209_ConnectionServer_3.0 (tgz of the whole Exasol logs directory can be found attached)

12.06 10:23:33.416 writeException: 40005 Successfully reconnected after internal server error, transaction was rolled back.

This does not seem to happen with the Exasol VM of the same version.

It happens if we do our automated regression tests but also if schedule loads like every 15 minutes: most of the complete ok but some of them show the server error.
[exasol-logs-20190612-102333.416.tgz.zip](https://github.com/exasol/docker-db/files/3281151/exasol-logs-20190612-102333.416.tgz.zip)

**Comment by exajuk** [comment]
If you are using version `6.1.3`, please open a shell in the terminal and execute `exasupport`, as soon as the error occurs again. This creates an archive containing all logs and coredumps (if any). Attach it to this issue.

**Comment by snehlsen** [comment]
We added this to our internal issue tracker and will analyze the problem, however we don't have an estimation yet. If you are already a customer we propose to create a regular support ticket which also simplifies sharing logfiles and potentially other information.

Can you please let us know what impact this issue has for you? Is there anything affected or blocked by this, or do you have a workaround?

**Comment by pbel78** [comment]
Hi. Thank you for the fast reply. We will do what you descsribed with the exasupport command. We are technical partners developing the Datavault Builder tool. All our regression tests run currently on the Exasol docker versions which makes us currently a little bit blind if we really have some serious issues or it is just this problem which doesn't appeaer in other settings. => so it means it's for us not a production issue which blocks us completely but costs us currently time for manual testing and potentially lets us oversee real bugs.

**Comment by snehlsen** [comment]
Thank you for the additional information. Can you open a ticket on https://www.exasol.com/support for this, so we can get more information to reproduce (DDLs for the schema of the failing query) this via the regular support process?

**Comment by pbel78** [comment]
We you able to solve the issue or did you just close it? Exasupport did not work in the container.

**Comment by pbel78** [comment]
Hallo Jürgen

Habt ihr das Problem behoben oder einfach geschlossen?

Gruss
Petr

Am Do., 25. Juli 2019 um 17:16 Uhr schrieb Jürgen Kadidlo <
notifications@github.com>:

**Comment by exajuk** [comment]
I've closed the Github issue because it has been transferred to our official support system. Please refer to the official issue for any new information. Thank you.
