### ISSUE TITLE
Run initialization scripts on first launch

### ISSUE THREAD

**Issue by reitzig** [exasol/docker-db#37]
In testing environment, we regularly want to start from scratch and initialize, say, a database schema. Currently, this image doesn't seem to support this and we have to run any scripts "manually".

Please add what amounts to a call like

```bash
exaplus -c n11:8888 -u sys -P exasol -f /init-db/*.sql
```

to the entrypoint script (potentially guarded by some criteria to ensure the container hasn't yet been initialized).

Precedence: [PostgreSQL official container](https://hub.docker.com/_/postgres#initialization-scripts)

**Comment by reitzig** [comment]
FWIW, I'd consider providing a PR but the current structure of this repo, which seems to include significant parts in that monstrous tarball, doesn't lend itself to that very well.

**Comment by reitzig** [comment]
Workaround: custom entrypoint (cf #39)

### Dockerfile

```Dockerfile
FROM exasol/docker-db

COPY init-db/*.sql /init-db/
COPY my-entrypoint.sh /

ENTRYPOINT /my-entrypoint.sh
CMD []
```

### my-entrypoint.sh

```bash
#!/bin/bash

set -e

exa_version=$(exaconf version)
exa_config="/exa/etc/EXAConf"

# Default entrypoint (but detach)
/usr/opt/EXASuite-6/EXAClusterOS-${exa_version}/docker/entrypoint.sh init-sc &

# Wait for initialization to be over:
while [[ $(ps -e | grep -wc exasql) -eq 0 ]]; do
    sleep 1
done

# Initialize database
for f in /init-db/*.sql; do
    exaplus -c n11:8888 -u sys -P exasol -f "${f}"
done

while [[ $(ps -e | grep -wc exasql) -gt 0 ]]; do
    sleep 1
done
echo "Process exasql no longer running; quitting. Check Exasol logs for details."
```

**Comment by ooke** [comment]
In future versions, you will be able to write such things into `/exa/etc/rc.local`. But it will not differentiate between first run and other runs, your script must then to figure out by self, what it need to do.

**Comment by anilbharadia** [comment]
@reitzig I tried to follow your suggestion of having a script to run sql files. However, I am getting following error: `exaplus: command not found`.

docker image: `exasol/docker-db:6.2.7-d1`
