### ISSUE TITLE
Configuring a nameserver for the container

### ISSUE THREAD

**Issue by dnno** [exasol/docker-db#39]
In order to access S3 buckets using the UDF jar provided by Exasol (also see: https://github.com/exasol/docker-db/issues/36), we have to set a nameserver in the container. We currently do this by waiting until the container has fully started (~90 sec) and then write a nameserver to the file **/etc/resolv.conf**. The README file for the container hints that you can set a nameserver in the EXAConf file, but it's not straightforward to do this.

I've tried to map the **/exa** folder inside the container to a host directory, set the nameserver there (also adjusting the checksum). As I don't want to add the complete **/exa** folder to version control, my goal would be to only have the **EXAConf** file in VCS, but it seems there is too much values configured on first startup and I cannot make the container start with this approach.

My question at this point is: what's the best way to set an initial name server for the container?

**Comment by exajuk** [comment]
The best was is to add the nameserver(s) to EXAConf before starting the container, e. g.

`NameServers = 10.10.0.53,10.10.0.54`

If you change the value while the container is running, you have to restart it (this may change in the future).

**Comment by reitzig** [comment]
Workaround: custom entrypoint script.

 1. Run `entrypoint.sh init-sc &`
 2. Wait for initialization do be over.
 3. Make changes to `EXAConf`.
 4. Run `init-sc` again.

### Dockerfile

```Dockerfile
FROM exasol/docker-db

COPY my-entrypoint.sh /
ENTRYPOINT /my-entrypoint.sh
CMD []
```

### my-entrypoint.sh

```bash
#!/bin/bash

set -e

exa_version=$(exaconf version)
exa_config="/exa/etc/EXAConf"

# Default entrypoint (but detach)
/usr/opt/EXASuite-6/EXAClusterOS-${exa_version}/docker/entrypoint.sh init-sc &

# Wait for initialization to be over:
while [[ $(ps -e | grep -wc exasql) -eq 0 ]]; do
    sleep 1
done

# Set nameserver so S3 can be found.
sed -i \
    -e 's/NameServers =[[:space:]]*$/NameServers = 8.8.8.8/' \
    -e 's/Checksum = .*$/Checksum = COMMIT/' \
    "${exa_config}"

# Load updated config
/usr/opt/EXASuite-6/EXAClusterOS-${exa_version}/docker/entrypoint.sh init-sc

while [[ $(ps -e | grep -wc exasql) -gt 0 ]]; do
    sleep 1
done
echo "Process exasql no longer running; quitting. Check Exasol logs for details."
```

Not sure how robust this will be; especially using `exasql` as a light tower feels fragile since I haven't understood the "flow" of the container fully.

**Comment by ooke** [comment]
I do not fully understand, why do you start it two times?

Important thing is, you should start `entrypoint.sh` only once with an `exec`, something like that (I have not tested it):
```
#!/bin/bash

set -e

exa_version=$(exaconf version)
exa_config="/exa/etc/EXAConf"

( # sub shell to leave PID 1 to the entry point
while true; do
    tail -n1 /exa/logs/cored/exainit.log | grep -q 'All stages finished.' && break
    sleep 1
done

# Set nameserver so S3 can be found.
sed -i \
    -e "s/NameServers =[[:space:]]*$/NameServers = ${NAMESERVER}/" \
    -e 's/Checksum = .*$/Checksum = COMMIT/' \
    "${exa_config}"

/usr/opt/EXASuite-6/EXAClusterOS-${exa_version}/bin/exalocalconf --function=name_resolution
while [[ $(pgrep -c exasql) -gt 0 ]]; do
    sleep 1
done
echo "Process exasql no longer running; quitting. Check Exasol logs for details."
pkill cos_cored
) &

exec /usr/opt/EXASuite-6/EXAClusterOS-${exa_version}/docker/entrypoint.sh init-sc

**Comment by reitzig** [comment]
> I do not fully understand, why do you start it two times?

It was the way I managed to create and then update the config. In particular, I tried `update-sc` but that didn't have the desired effect. I didn't find `exalocalconf` with this parameterization.

Is there a particular reason you wait for that log line instead of `exasql`?

It doesn't seem to be necessary to keep that subshell alive, assuming that the regular entrypoint hands off to something that appropriately dies in case of issues. Or am I missing something?

Good call on the subshell! The PID trickeries are a little beyond me, but it's certainly the better approach to set up a "callback", for lack of a better word.

Currently using this:

```bash
#!/bin/bash

set -e

exa_version=$(exaconf version)
exa_config="/exa/etc/EXAConf"
exa_localconf="/usr/opt/EXASuite-6/EXAClusterOS-${exa_version}/bin/exalocalconf"
exa_entrypoint="/usr/opt/EXASuite-6/EXAClusterOS-${exa_version}/docker/entrypoint.sh"

( # sub shell to leave PID 1 to the entry point
    # Wait for initialization to be over:
    while [[ $(ps -e | grep -wc exasql) -eq 0 ]]; do
        sleep 1 # TODO: Add timeout? Or how else do we detect failure of init-sc?
    done

    echo "[my-project] Set nameserver to ${NAMESERVER}" # so S3 can be found.
    sed -i \
        -e "s/NameServers =[[:space:]]*$/NameServers = ${NAMESERVER}/" \
        -e 's/Checksum = .*$/Checksum = COMMIT/' \
        "${exa_config}"
    "${exa_localconf}" --function=name_resolution

    echo "[my-project] Initialize database"
    for f in /init-db/*.sql; do
        echo "[my-project] Running ${f}"
        exaplus -c n11:8888 -u sys -P exasol -f "${f}"
    done

    echo "[my-project] Customization finished"
) & # --> let Exasol entrypoint take over

exec "${exa_entrypoint}" init-sc
```

Thanks for the help!

**Comment by ooke** [comment]
I think, it could make sense to wait to one of the following things, each has own drawbacks:
# Wait for existance of `exasql` process
#- It has the drawback, that it is not guaranteed, that the initialization process is finished or the database is ready for requests, but usually it is.
# Wait for `dwad_client print-params DB1 2>/dev/null | grep -q '^Connection state: up'`
#- It guarantees, that the database is ready for requests, but not, that the initialization process is finished.
# Wait for `All stages finished.`
#- It guarantees, that the initialization is finished and database is ready to receive requests, it is still possible that some error happens or database crashes shortly after that, but this is other story.
#- It has the drawback, that you waiting on a log file, it is not 100% clear, how robust it is.

So the waiting for the line in the log file seem to cover all the cases, so I think it is may be the better way to go, but also the first case should work fine.

**Comment by reitzig** [comment]
I see, thanks for the explanation.
(FWIW, I kept tinkering and improved the version you reacted to.)

With the `exainit.log` variant (3), I'm getting

```
EXAplus 6.1.5 (c) EXASOL AG
Error: [08001] Connection refused (Connection refused)
```

I figure this means something is not quite up. I never saw this with variant (1) so I'll back to that and see how reliable it is.

**Comment by ooke** [comment]
Oh, ok. I have checked the code, you are right, the `exainit.log` variant does not really wait for the database be connectable, but I think it should. I will fix that.

**Comment by ooke** [comment]
The behavior is fixed, so you will be able to wait for the initialization also on `All stages finished`, but the more strait forward approach will be to write such things to `/exa/etc/rc.local`.
