### ISSUE TITLE
Add a meaningful healthcheck

### ISSUE THREAD

**Issue by reitzig** [exasol/docker-db#40]
It can be hard to tell when the service is ready for requests. I added

```Dockerfile
HEALTHCHECK CMD test $(ps -e | grep -wc exasql) -gt 0
```

but I have no way of knowing how conclusive that is.

On a related note, I'd appreciate documentation of a meaningful _smoke test_ from the outside.

**Comment by wildraid** [comment]
The most reliable smoke test is just opening a connection. It also checks many other things, like "ConnectionServer" availability and DNS records validity.

**Comment by reitzig** [comment]
How do I "just open a connection", though, without having to installing the full Java or Python dependencies? Is there a meaningful `curl` (or similar) I could run? Is there a low-weight client like `psql`?

**Comment by ooke** [comment]
You can always check with `dwad_client print-params DB1 2>/dev/null | grep -q '^Connection state: up'` whether the database is ready for requests (instead of DB1 there should be the actual name).

**Comment by reitzig** [comment]
I'm getting (in a container running an SC instance):

```
$ dwad_client print-params DB1
Log_E: [2019-09-19 11:13:32] <140655974007680> unix_auth.cc:216 register_unix_client(): Authentication service could not register this process: 
Could not start dwad_client: e_perm - ERROR 00009: [interface] Permission denied. Process not in COS cluster?!
```

**Comment by ooke** [comment]
Yes, this is possible, as long the cluster do not running, it takes some seconds to start the services. If I start it on a running container, then it works:
```
# docker exec -it cc9d4214ec86 dwad_client print-params DB1
List parameters of system DB1.
+++++++++++++++++++++++++++++++++++++++++++++
Name: DB1
State: running
Connection state: up
16 state comments available.
-----
[2019-08-29 15:33:17] System is ready to receive client connections.
[2019-08-29 15:36:42] All processes stopped.
[2019-08-29 15:36:47] (UID 0) User requested setup of system.
[2019-08-29 15:36:47] (UID 0) Try to start system.
[2019-08-29 15:36:48] System started successfully in partition 24.
[2019-08-29 15:36:58] System is ready to receive client connections.
[2019-09-19 10:56:45] All processes stopped.
[2019-09-19 10:56:50] (UID 0) User requested setup of system.
[2019-09-19 10:56:50] (UID 0) Try to start system.
[2019-09-19 10:56:50] System started successfully in partition 24.
[2019-09-19 10:56:59] System is ready to receive client connections.
[2019-09-19 11:30:43] All processes stopped.
[2019-09-19 11:30:48] (UID 0) User requested setup of system.
[2019-09-19 11:30:48] (UID 0) Try to start system.
[2019-09-19 11:30:48] System started successfully in partition 24.
[2019-09-19 11:30:57] System is ready to receive client connections.
-----
Parameters: "/usr/opt/EXASuite-6/EXAClusterOS-6.2.0/bin/dwa_wrapper -dbName DB1 -commMain n11 -commNPROC 2 -port 8888 -mode rw -outputdir /exa/logs/db/DB1/ -netmask= -auditing_enabled=0 -lockslb=1 -sandboxPath=/usr/opt/mountjail -cosLogErrors=0 -bucketFSConfigPath=/exa/etc/bucketfs_db.cfg -sysTZ=Europe/Berlin -etlJdbcConfigDir=/exa/data/bucketfs/bfsdefault/.dest/default/drivers/jdbc:/usr/opt/EXASuite-6/3rd-party/JDBC/@JDBCVERSION@:/usr/opt/EXASuite-6/EXASolution-6.2.0/jdbc -dbram 2048 -pers_volume_id 0 -wrapper /usr/opt/EXASuite-6/EXASolution-6.2.0/bin/controller -logdir /exa/logs/db/DB1/ -wrapper-short-datafilenames"
Active host(s): n11, n12
+++++++++++++++++++++++++++++++++++++++++++++
```

If you use own entry point, than important thing is, that the original docker entry point get the PID 1, because at the end `cos_cored` process inside the process namespace of the container need to have PID 1 to be default parent of all other processes and work as `init` inside the container (usual linux thing).

**Comment by reitzig** [comment]
Ah yes, my mangling of PIDs in the custom entrypoint script was responsibe, apparently. With the [updated version](https://github.com/exasol/docker-db/issues/39#issuecomment-533085475) it works. Thanks!

**Comment by ooke** [comment]
In future versions you will also get the possibility to write your initialization things to a `/exa/etc/rc.local` file, which will be executed in different stages and also at the end after the db is up and running.

**Comment by reitzig** [comment]
@ooke How does that feature enable me to query container health hours after startup?
