### ISSUE TITLE
Need further advice on Hugepages feature

### ISSUE THREAD

**Issue by HEP85** [exasol/docker-db#49]
The documentation on hugepages optimization seems lacking. My experience:

What I did:
- disabled transparent hugepages in kernel
- set hugepage size to 2048KiB
- set hugepage count to around 90% of RAM / hugepage size
- set EXAConf setting to "auto"

What I got:
- after resource intensive workload was started, DB became totally unresponsive
- on one of the nodes even typing in SSH was delayed because of load
- top showing very high CPU usage on kswapd0 at one node
- strangely enoughproblem was not distributed equally across nodes

Questions:
- Is there another setting to change for it to work? I heard of changing memlock limits from other DBMS
- What about the Hugepages EXAConf option: should I set it to "auto" or "host", what is better?
- When setting it to "host" I get the warning "stage3: WARNING: Hugepages could not be set to value 0, current value 22456" Can I ignore that one?
- Are 90% too many hugepages, so maybe kernel is starving? What is the ideal value? Should I try with 70%

Any suggestions?

**Comment by ooke** [comment]
Please set it to `auto` and remove any configurations in the host. With this option you should see the recommended amount. The warning can be ignored, it just shows that the system has not set it by self.

**Comment by HEP85** [comment]
Yes, auto seems to be the way to go. With manual I was experiencing "Out of memory" internal errors and coredumps of pddserver.

**Comment by ooke** [comment]
It is possible to configure it manually on host, but it seems, that 22456 is just too big. The `auto` configuration avoid the possibility to create too much huge pages by mistake.
