### ISSUE TITLE
Failed to connect to oracle

### ISSUE THREAD

**Issue by 555chy** [exasol/docker-db#58]
I use this command to install driver for oracle in docker container

$ curl -v -X PUT -T instantclient-basic-linux.x64-12.1.0.2.0.zip http://w:PASSWORD@10.10.10.11:2580/default/drivers/oracle/instantclient-basic-linux.x64-12.1.0.2.0.zip

But cannot connect to this IP, tip such as

*   Trying 10.10.10.11:2580...
* TCP_NODELAY set
* connect to 10.10.10.11 port 2580 failed: Connection timed out
* Failed to connect to 10.10.10.11 port 2580: Connection timed out
* Closing connection 0

**Comment by frschwab** [comment]
Hi,
it seems like you are trying to use the docker network address, but you should use your local address and configure this 2580 port as port forwarding in docker.
I don't know where your docker setup is running, so IP might be correct, but maybe port forwarding missing.
Please check your network configuration and keep us posted!

**Comment by 555chy** [comment]
I make a mistake before.
Now, I use this command to get the WritePasswd

> awk '/WritePasswd/{ print $3; }' /exa/etc/EXAConf | base64 -d

And then download the lasted version of instantclient at oracle office website

> instantclient-basic-linux.x64-21.1.0.0.0.zip

Use docker cp command to put it into docker

The i use follow command to put files into target place, of course it's run success!
And them show at /exa/data/bucketfs/bfsdefault/.dest/default/drivers/oracle finally

> curl -v -X PUT -T instantclient-basic-linux.x64-21.1.0.0.0.zip http://w:0wKbnBzk1GGKweNrqWtf5K@172.17.0.2:2580/default/drivers/oracle/instantclient-basic-linux.x64-21.1.0.0.0.zip
> 
> curl -v -X PUT -T settings.cfg http://root:0wKbnBzk1GGKweNrqWtf5K@172.17.0.2:2580/default/drivers/oracle/settings.cfg


settings.cfg

> DRIVERNAME=ORACLE
> JAR=instantclient-basic-linux.x64-21.1.0.0.0.zip
> DRIVERMAIN=oracle.jdbc.OracleDriver
> PREFIX=jdbc:oracle:thin:
> FETCHSIZE=100000
> INSERTSIZE=-1

But when i run sql, it's fail, the tip is 

> Oracle instant client not available. Please ask your administrator to install it via EXAoperation. (Session: 1693016232771780608)

**Comment by 555chy** [comment]
> Hi,
> it seems like you are trying to use the docker network address, but you should use your local address and configure this 2580 port as port forwarding in docker.
> I don't know where your docker setup is running, so IP might be correct, but maybe port forwarding missing.
> Please check your network configuration and keep us posted!

Can you helo me T_T ?

**Comment by 555chy** [comment]
I resolve it.  The IP must be in EXAConf which maybe not equal with README.md.

For example,  in EXAConf, my ip is 172.17.0.2

[Node : 11]
    PrivateNet = 172.17.0.2/16
