### ISSUE TITLE
exadt does not work on docker for windows

### ISSUE THREAD

**Issue by rgizm0** [EXASOL/docker-db#6]
Trying to run docker on Windows 10. I have this error
python exadt init-cluster --image exasol/docker-db:6.0.0-d1 --license ./license.xml --device-type file --auto-storage --force MyCluster
Traceback (most recent call last):
  File "exadt", line 712, in <module>
    main()
  File "exadt", line 709, in main
    command.func(command)
  File "exadt", line 260, in init_cluster
    license = cmd.license)
  File "C:\Users\ruge\GitHub\docker-db\libexadt\EXAConf.py", line 331, in initialize
    data_vol_sec["Owner"] = str(os.getuid()) + " : " + str(os.getgid())
AttributeError: 'module' object has no attribute 'getuid'

There seems to be a fix described here https://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python

**Comment by ooke** [comment]
It looks like the docker version for windows is not supported by exadt yet, please use a real linux VM instead or start the self contained version of the image (without exadt).

**Comment by exajuk** [comment]
Release 6.0.1 contains a fix for this issue. Docker for Windows is still unsupported, though.
