### ISSUE TITLE
Issue with default bucketfs in 7.1

### ISSUE THREAD

**Issue by wildraid** [exasol/docker-db#64]
Something is not right with default container in bucketfs in 7.1.

```
Traceback (most recent call last):
  File "examples/00_prepare.py", line 172, in <module>
    """)
  File "/home/travis/build/badoo/pyexasol/pyexasol/connection.py", line 193, in execute
    return self.cls_statement(self, query, query_params)
  File "/home/travis/build/badoo/pyexasol/pyexasol/statement.py", line 55, in __init__
    self._execute()
  File "/home/travis/build/badoo/pyexasol/pyexasol/statement.py", line 159, in _execute
    'sqlText': self.query,
  File "/home/travis/build/badoo/pyexasol/pyexasol/connection.py", line 579, in req
    raise cls_err(self, req['sqlText'], ret['exception']['sqlCode'], ret['exception']['text'])
pyexasol.exceptions.ExaQueryError: 
(
    message     =>  BucketFS: root path 'EXAClusterOS/ScriptLanguages-release-standard-exasol-7.1.0-1.1.0'' does not exist in bucket 'default' of bucketfs 'bfsdefault' (Session: 1707086082210004992)
    dsn         =>  127.0.0.1:8563
    user        =>  SYS
    schema      =>  PYEXASOL_TEST
    session_id  =>  1707086082210004992
    code        =>  42000
    query       =>  CREATE OR REPLACE JAVA SET SCRIPT "ECHO_JAVA" ("str" VARCHAR(255) UTF8) RETURNS VARCHAR(255) UTF8 AS
%jvmoption -Xms16m -Xmx128m -Xss512k;
```

More logs: https://app.travis-ci.com/github/badoo/pyexasol/jobs/528801487

Thank you.

**Comment by wildraid** [comment]
Just try to create any JAVA script with default container and without touching any settings.

**Comment by tkilias** [comment]
Thanks @wildraid, I will have a look.

**Comment by tkilias** [comment]
Hi @wildraid,

we released a new version of the image under the following names, which should solve the problem.

```
docker pull exasol/docker-db:7.1.0-d1
docker pull exasol/docker-db:latest-7.1
docker pull exasol/docker-db:latest
```

**Comment by wildraid** [comment]
Now I've got this message:

```
message     =>  BucketFS: File '/exaudf/exaudfclient' does not exist. (Session: 1707266627197665280)
```

More logs: https://app.travis-ci.com/github/badoo/pyexasol/jobs/528801487

**Comment by tkilias** [comment]
Hi @wildraid,

From what I saw, when I tested the images. It requires a few minutes between you started it and when the Language Container is fully extracted. That the error message changed is a clear sign, that Language Container directory exists, but is not yet completely there.

**Comment by wildraid** [comment]
I've tried to increase the sleep time by 40 seconds (120 -> 160). It did not help, same error.

Logs: https://app.travis-ci.com/github/badoo/pyexasol/jobs/529749522

**Comment by tkilias** [comment]
I roughly measured the time. It seems to take around 4 minutes from starting the docker container until it is completely extracted.

**Comment by wildraid** [comment]
Why did it increase so much? Is there any way to detect the end of extraction programmatically?

"sleep" is kinda lame solution :)

**Comment by tkilias** [comment]
File 'default/EXAClusterOS/ScriptLanguages-release-standard-exasol-7.1.0-1.1.0.tar.gz' extracted

**Comment by wildraid** [comment]
Ok, I've increased the sleep delay, and it works for now. And I've some other issues.

Travis is working with Pyexasol + Exasol 7.1.

In theory, it would be nice to have a simple & universal way to check if BucketFS is ready. But it can wait.

Thank you!
