### ISSUE TITLE
Difference between version 7.1.0 and 7.1.0-d1

### ISSUE THREAD

**Issue by walter-weinmann** [exasol/docker-db#65]
What is the difference between these two Image versions?

![image](https://user-images.githubusercontent.com/1956149/129324306-7c458738-45c3-4e89-8f9c-af07ae96d577.png)

**Comment by tkilias** [comment]
Hello @walter-weinmann,

Thank you for the question. The docker-db:7.1.0-d1 image is a bugfix for the docker-image which was necessary to fix the following issue https://github.com/exasol/docker-db/issues/64. The previous image (docker-db:7.1.0) didn't extract the built-in script-language container, which caused the UDFs to not work out of the box.

**Comment by walter-weinmann** [comment]
Thanks @tkilias
