### ISSUE TITLE
Connecting to EXAoperation

### ISSUE THREAD

**Issue by Jesterreborn** [EXASOL/docker-db#7]
Is EXAoparation included with docker version? If it is what's the url to use?

**Comment by ooke** [comment]
No, EXAoperation is not included in the docker version, the configuration should be made with the EXAConf file, this file is explained in the README: https://github.com/EXASOL/docker-db/blob/master/README.md

**Comment by hoffmann** [comment]
We are using the docker verIsion in our test setup. It would be helpful if we could also do this to test the exaoperations XML RPC Interface. Should I place this as a feature request within Exasol or can you forward/priorize this?
