### ISSUE TITLE
Exasol docker-db for Windows host

### ISSUE THREAD

**Issue by hlms** [exasol/docker-db#75]
Hello team,

The documentation which was last updated 2 years ago mentions:

> We currently only support Docker on Linux. If you are using a Windows host you'd have to create a Linux VM.

Is it still the case? Or is it supported on Windows host now?

**Comment by hlms** [comment]
@CK1979 ,  
Could you answer this query?

**Comment by CK1979** [comment]
yes, we still only support Linux
