### ISSUE TITLE
unable connect to oracle

### ISSUE THREAD

**Issue by agntdv** [EXASOL/docker-db#8]
Hi, 

I am trying to connect to Oracle server from docker container`s exaplus and it is asking for Oracle drivers. How do I install instant client into the container or how to access EXAoperation? 

SQL_EXA> select * from
1    > (
2    > import from ora at ora_connection
3    > USER 'system' IDENTIFIED BY 'oracle'
4    > statement 'select * from dual'
5    > );
EXA: select * from ...
Error: [ETL-4] Oracle instant client not available. Please ask your administrator to install it via EXAoperation. (Session: 1570714493703753727)
SQL_EXA>

Thank you, 
Azat

**Comment by ooke** [comment]
Docker version of the DB has no EXAoperation as in full installations. Here I have created a test Dockerfile, which creates an image with integrated Oracle Client:
```
FROM centos:6.8

MAINTAINER EXASOL "service@exasol.com"

RUN yum update -y --exclude=kernel* && \
    yum install -y \
    java-1.8.0-openjdk-headless \
    openssh-server \
    openssh-client \
    which \
    sudo \
    vim \
    unzip \
    tar \
    rsync && \
    yum clean all

LABEL name="EXASOL DB Docker Image"  \
      version="6.0.2-d1" \
      dbversion="6.0.2" \
      osversion="6.0.2" \
      reversion="6.0.2" \
      license="Proprietary" \
      vendor="EXASOL AG"


COPY license.xml     /.license.xml
ADD EXAClusterOS-6.0.3_LS-DOCKER-CentOS-6.8_x86_64.tar.gz              /
ADD instantclient-basic-linux.x64-12.2.0.1.0.zip                       /
ENV PATH=/usr/opt/EXASuite-6/EXAClusterOS-6.0.2/bin:/usr/opt/EXASuite-6/EXAClusterOS-6.0.2/sbin:/usr/opt/EXASuite-6/EXARuntime-6.0.2/bin:/usr/opt/EXASuite-6/EXARuntime-6.0.2/sbin:/usr/op/EXASuite-6/EXASolution-6.0.2/bin/Console:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    EXA_IMG_VERSION="6.0.2-d1" \
    EXA_DB_VERSION="6.0.2" \
    EXA_OS_VERSION="6.0.2" \
    EXA_RE_VERSION="6.0.2" 


RUN mkdir -p /usr/opt/EXASuite-6/3rd-party/Oracle && cd /usr/opt/EXASuite-6/3rd-party/Oracle && \
    unzip /instantclient-basic-linux.x64-12.2.0.1.0.zip && cd instantclient_12_2 && \
    rm -f /instantclient-basic-linux.x64-12.2.0.1.0.zip && mkdir lib && \
    ( cd lib && ln -vs ../*.so ../*.so.* . ) && \
    ( cd lib && for f in *.12.1; do ln -vs $f ${f%.12.1}; done ) && \
    ( cd lib && for f in *12.so; do ln -vs $f ${f%12.so}; done ) && \
    sed -i.orig -e 's|/usr/lib64/libnuma.so|libnuma.so\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0|;s|/usr/lib64/libnuma.so.1|libnuma.so.1\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0|' "libclntsh.so.12.1" && \
    chown -R 0:0 .

ENTRYPOINT ["/usr/opt/EXASuite-6/EXAClusterOS-6.0.2/devel/docker/exadt"]
CMD ["init-sc"]
```

You will need this file for it:
```
d9639092e3dea2e023272e52e2bd42da  instantclient-basic-linux.x64-12.2.0.1.0.zip
```

**Comment by agntdv** [comment]
Hi @ooke 

I have tried to build the image based on original Dockerfile (ver 3 and 4) and based on the above Dockerfile as follows, still no luck :(

where would you suggest to look?

`]# docker build -t my-exasol .`

`]# docker run --detach --privileged --stop-timeout 120 -p 6583:6583 -p 8888:8888 my-exasol`

> f7efe41e25245c23db9a7fa041bac22e22c8557f002a035d8c9f380d3185c836
> docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/opt/EXASuite-6/EXAClusterOS-6.0.4/devel/docker/exadt\": stat /usr/opt/EXASuite-6/EXAClusterOS-6.0.4/devel/docker/exadt: no such file or directory".
> 

Thanks

**Comment by agntdv** [comment]
I`ve also tried to deploy oracle instant into the container based on latest pulled docker image using the fragment you provided, still no luck, somehow Exasol is not seeing the libs:

```
mkdir -p /usr/opt/EXASuite-6/3rd-party/Oracle && cd /usr/opt/EXASuite-6/3rd-party/Oracle && \
    unzip /instantclient-basic-linux.x64-12.2.0.1.0.zip && cd instantclient_12_2 && \
    rm -f /instantclient-basic-linux.x64-12.2.0.1.0.zip && mkdir lib && \
    ( cd lib && ln -vs ../*.so ../*.so.* . ) && \
    ( cd lib && for f in *.12.1; do ln -vs $f ${f%.12.1}; done ) && \
    ( cd lib && for f in *12.so; do ln -vs $f ${f%12.so}; done ) && \
    sed -i.orig -e 's|/usr/lib64/libnuma.so|libnuma.so\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0|;s|/usr/lib64/libnuma.so.1|libnuma.so.1\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0|' "libclntsh.so.12.1" && \
    chown -R 0:0 .
```

> [ETL-4] Oracle instant client not available. Please ask your administrator to install it via EXAoperation. (Session: 1582964791103062899)

**Comment by exajuk** [comment]
Oracle driver support has been added in version 6.0.7.
